-- QUÉX — banco de dados para Supabase
-- Execute este arquivo no SQL Editor do projeto Supabase.
-- O schema foi desenhado para funcionar diretamente com o front-end Vercel.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  role text not null default 'buyer' check (role in ('buyer','seller')),
  cpf text,
  cpf_cnpj text,
  phone text not null default '',
  business_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists full_name text not null default '';
alter table public.profiles add column if not exists role text not null default 'buyer';
alter table public.profiles add column if not exists cpf text;
alter table public.profiles add column if not exists cpf_cnpj text;
alter table public.profiles add column if not exists phone text not null default '';
alter table public.profiles add column if not exists business_name text;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create unique index if not exists profiles_cpf_unique on public.profiles (cpf) where cpf is not null and cpf <> '';
create unique index if not exists profiles_cpf_cnpj_unique on public.profiles (cpf_cnpj) where cpf_cnpj is not null and cpf_cnpj <> '';
create index if not exists profiles_role_idx on public.profiles(role);

create table if not exists public.produto (
  id bigint generated by default as identity primary key,
  vendedor_id uuid references auth.users(id) on delete set null,
  vendedor_email text,
  vendedor_nome text,
  nome text not null,
  categoria text not null default 'peixe' check (categoria in ('peixe','iguaria')),
  especie text not null default '',
  descricao text,
  preco numeric(12,2) not null check (preco > 0),
  quantidade numeric(12,2) not null default 0 check (quantidade >= 0),
  unidade text not null default 'kg' check (unidade in ('kg','unit','dozen')),
  ativo boolean not null default true,
  fotos_url text,
  tem_espinha boolean not null default false,
  tipo_agua text not null default 'doce' check (tipo_agua in ('doce','salgada')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.produto add column if not exists vendedor_id uuid;
alter table public.produto add column if not exists vendedor_email text;
alter table public.produto add column if not exists vendedor_nome text;
alter table public.produto add column if not exists nome text;
alter table public.produto add column if not exists categoria text default 'peixe';
alter table public.produto add column if not exists especie text default '';
alter table public.produto add column if not exists descricao text;
alter table public.produto add column if not exists preco numeric(12,2);
alter table public.produto add column if not exists quantidade numeric(12,2) default 0;
alter table public.produto add column if not exists unidade text default 'kg';
alter table public.produto add column if not exists ativo boolean default true;
alter table public.produto add column if not exists fotos_url text;
alter table public.produto add column if not exists tem_espinha boolean default false;
alter table public.produto add column if not exists tipo_agua text default 'doce';
alter table public.produto add column if not exists created_at timestamptz default now();
alter table public.produto add column if not exists updated_at timestamptz default now();

create index if not exists produto_ativo_idx on public.produto(ativo);
create index if not exists produto_vendedor_idx on public.produto(vendedor_id);
create index if not exists produto_especie_idx on public.produto(especie);
create index if not exists produto_categoria_idx on public.produto(categoria);

create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.produto(id) on delete cascade,
  product_name text not null,
  product_price numeric(12,2) not null,
  product_image text,
  seller_name text,
  quantity numeric(12,2) not null default 1 check (quantity > 0),
  subtotal numeric(12,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(buyer_id, product_id)
);

create index if not exists cart_items_buyer_idx on public.cart_items(buyer_id);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references auth.users(id) on delete restrict,
  buyer_name text,
  total numeric(12,2) not null default 0,
  status text not null default 'pending' check (status in ('pending','paid','preparing','dispatched','delivered','cancelled')),
  delivery_address text not null default '',
  tracking_code text,
  delivery_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_buyer_idx on public.orders(buyer_id);
create index if not exists orders_status_idx on public.orders(status);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.produto(id) on delete restrict,
  seller_id uuid references auth.users(id) on delete set null,
  seller_name text,
  product_name text not null,
  quantity numeric(12,2) not null check (quantity > 0),
  unit_price numeric(12,2) not null,
  subtotal numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_items_seller_idx on public.order_items(seller_id);

-- Perfil automático após cadastro pelo Supabase Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role, cpf, cpf_cnpj, phone, business_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'role', 'buyer'),
    nullif(new.raw_user_meta_data ->> 'cpf', ''),
    nullif(new.raw_user_meta_data ->> 'cpf_cnpj', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    nullif(new.raw_user_meta_data ->> 'business_name', '')
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = excluded.full_name,
    role = excluded.role,
    cpf = excluded.cpf,
    cpf_cnpj = excluded.cpf_cnpj,
    phone = excluded.phone,
    business_name = excluded.business_name,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Permissões e RLS.
alter table public.profiles enable row level security;
alter table public.produto enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.produto from anon, authenticated;
revoke all on table public.cart_items from anon, authenticated;
revoke all on table public.orders from anon, authenticated;
revoke all on table public.order_items from anon, authenticated;

grant select on public.produto to anon, authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.produto to authenticated;
grant select, insert, update, delete on public.cart_items to authenticated;
grant select, update on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create schema if not exists private;
create or replace function private.is_seller(uid uuid default auth.uid())
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (select 1 from public.profiles p where p.id = uid and p.role = 'seller');
$$;
revoke all on function private.is_seller(uuid) from public;
grant usage on schema private to authenticated;
grant execute on function private.is_seller(uuid) to authenticated;

drop policy if exists "public can view active products" on public.produto;
drop policy if exists "seller manages own products" on public.produto;
create policy "public can view active products" on public.produto for select to anon using (ativo = true);
create policy "authenticated can view products" on public.produto for select to authenticated using (ativo = true or vendedor_id = auth.uid());
create policy "seller inserts own products" on public.produto for insert to authenticated with check (private.is_seller() and vendedor_id = auth.uid());
create policy "seller updates own products" on public.produto for update to authenticated using (private.is_seller() and vendedor_id = auth.uid()) with check (private.is_seller() and vendedor_id = auth.uid());
create policy "seller deletes own products" on public.produto for delete to authenticated using (private.is_seller() and vendedor_id = auth.uid());

-- Impede que um comprador altere o próprio papel para vendedor via REST.
create or replace function public.prevent_profile_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and old.role is distinct from new.role then
    new.role := old.role;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_role on public.profiles;
create trigger protect_profile_role
before update on public.profiles
for each row execute procedure public.prevent_profile_role_change();

drop policy if exists "users read own profile" on public.profiles;
drop policy if exists "users update own profile" on public.profiles;
drop policy if exists "users insert own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select to authenticated using (id = auth.uid());
create policy "users insert own profile" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "users update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "buyers manage own cart" on public.cart_items;
create policy "buyers view own cart" on public.cart_items for select to authenticated using (buyer_id = auth.uid());
create policy "buyers insert own cart" on public.cart_items for insert to authenticated with check (buyer_id = auth.uid());
create policy "buyers update own cart" on public.cart_items for update to authenticated using (buyer_id = auth.uid()) with check (buyer_id = auth.uid());
create policy "buyers delete own cart" on public.cart_items for delete to authenticated using (buyer_id = auth.uid());

create or replace function private.is_order_seller(order_uuid uuid, uid uuid default auth.uid())
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1 from public.order_items oi
    where oi.order_id = order_uuid and oi.seller_id = uid
  );
$$;
revoke all on function private.is_order_seller(uuid, uuid) from public;
grant execute on function private.is_order_seller(uuid, uuid) to authenticated;

create or replace function private.is_order_buyer(order_uuid uuid, uid uuid default auth.uid())
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1 from public.orders o
    where o.id = order_uuid and o.buyer_id = uid
  );
$$;
revoke all on function private.is_order_buyer(uuid, uuid) from public;
grant execute on function private.is_order_buyer(uuid, uuid) to authenticated;

drop policy if exists "buyers and sellers view relevant orders" on public.orders;
drop policy if exists "sellers update relevant orders" on public.orders;
create policy "buyers and sellers view relevant orders" on public.orders for select to authenticated using (
  buyer_id = auth.uid() or private.is_order_seller(id, auth.uid())
);
create policy "sellers update relevant orders" on public.orders for update to authenticated using (
  private.is_seller() and private.is_order_seller(id, auth.uid())
) with check (private.is_seller() and private.is_order_seller(id, auth.uid()));

drop policy if exists "users view relevant order items" on public.order_items;
create policy "users view relevant order items" on public.order_items for select to authenticated using (
  seller_id = auth.uid() or private.is_order_buyer(order_id, auth.uid())
);

-- Checkout transacional: confere estoque, cria pedido, baixa estoque e limpa o carrinho.
create or replace function public.quex_create_order(p_items jsonb, p_delivery_address text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  order_id uuid;
  buyer_name text;
  entry jsonb;
  product_row public.produto%rowtype;
  qty numeric;
  total numeric := 0;
begin
  if uid is null then raise exception 'Usuário não autenticado.' using errcode = '42501'; end if;
  if jsonb_array_length(coalesce(p_items, '[]'::jsonb)) = 0 then raise exception 'Carrinho vazio.'; end if;

  select full_name into buyer_name from public.profiles where id = uid;
  if not exists (select 1 from public.profiles where id = uid and role = 'buyer') then
    raise exception 'Apenas compradores podem finalizar pedidos.' using errcode = '42501';
  end if;
  if coalesce(trim(p_delivery_address), '') = '' then raise exception 'Endereço de entrega obrigatório.'; end if;

  for entry in select * from jsonb_array_elements(p_items)
  loop
    qty := greatest(0, (entry ->> 'quantity')::numeric);
    if qty <= 0 then raise exception 'Quantidade inválida.'; end if;

    select * into product_row from public.produto where id = (entry ->> 'product_id')::bigint for update;
    if not found then raise exception 'Produto não encontrado.'; end if;
    if product_row.ativo is not true then raise exception 'Produto indisponível: %', product_row.nome; end if;
    if product_row.quantidade < qty then raise exception 'Estoque insuficiente para: %', product_row.nome; end if;
    total := total + (product_row.preco * qty);
  end loop;

  insert into public.orders (buyer_id, buyer_name, total, status, delivery_address)
  values (uid, buyer_name, total, 'pending', trim(p_delivery_address))
  returning id into order_id;

  for entry in select * from jsonb_array_elements(p_items)
  loop
    qty := (entry ->> 'quantity')::numeric;
    select * into product_row from public.produto where id = (entry ->> 'product_id')::bigint for update;

    insert into public.order_items (order_id, product_id, seller_id, seller_name, product_name, quantity, unit_price, subtotal)
    values (order_id, product_row.id, product_row.vendedor_id, product_row.vendedor_nome, product_row.nome, qty, product_row.preco, qty * product_row.preco);

    update public.produto
    set quantidade = quantidade - qty,
        ativo = case when quantidade - qty <= 0 then false else ativo end,
        updated_at = now()
    where id = product_row.id;

    delete from public.cart_items where buyer_id = uid and product_id = product_row.id;
  end loop;

  update public.orders set updated_at = now() where id = order_id;
  return (select to_jsonb(o) from public.orders o where o.id = order_id);
end;
$$;
revoke all on function public.quex_create_order(jsonb, text) from public;
grant execute on function public.quex_create_order(jsonb, text) to authenticated;

-- Dados de demonstração para uma instalação nova. Não pertencem a nenhum vendedor.
insert into public.produto (vendedor_id, vendedor_email, vendedor_nome, nome, categoria, especie, descricao, preco, quantidade, unidade, ativo, fotos_url, tem_espinha, tipo_agua)
select null, null, 'QUÉX Demo', x.nome, x.categoria, x.especie, x.descricao, x.preco, x.quantidade, x.unidade, true, x.fotos_url, x.tem_espinha, x.tipo_agua
from (values
  ('Tilápia Fresca','peixe','Tilápia','Tilápia fresca para grelha ou filé, com textura leve e sabor suave.',29.90,18,'kg','https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&h=680&fit=crop',true,'doce'),
  ('Sardinha Limpa','peixe','Sardinha','Sardinha fresca já limpa para assar, fritar ou preparar em conserva.',21.50,12,'kg','https://images.unsplash.com/photo-1510130387422-1e0e8cbb0e4e?w=900&h=680&fit=crop',true,'salgada'),
  ('Camarão Rosa','iguaria','Camarão','Camarão rosa selecionado, ideal para moquecas, massas e risotos.',69.90,9,'kg','https://images.unsplash.com/photo-1565680018093-ebb6c9cf1d5d?w=900&h=680&fit=crop',false,'salgada'),
  ('Mexilhão Fresco','iguaria','Mexilhão','Mexilhões frescos para receitas à base de frutos do mar.',32.00,14,'kg','https://images.unsplash.com/photo-1559737558-2f5a35f4523f?w=900&h=680&fit=crop',false,'salgada'),
  ('Pescada Branca','peixe','Pescada','Carne branca e macia, ótima para assados, ensopados e preparos do dia a dia.',34.90,10,'kg','https://images.unsplash.com/photo-1534040111752-7b1d0c5b0f5d?w=900&h=680&fit=crop',true,'salgada'),
  ('Filé de Tilápia','peixe','Tilápia','Filé sem espinha, prático para receitas rápidas e preparo na frigideira.',39.90,11,'kg','https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=900&h=680&fit=crop',false,'doce')
) as x(nome,categoria,especie,descricao,preco,quantidade,unidade,fotos_url,tem_espinha,tipo_agua)
where not exists (select 1 from public.produto p where p.nome = x.nome and p.vendedor_nome = 'QUÉX Demo');

-- Observação: a chave anon é a chave pública do cliente Supabase. A segurança real vem das políticas RLS.
