import React, { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, CheckCircle2, MapPin, CreditCard } from 'lucide-react'
import toast from 'react-hot-toast'
import { checkout, listCart } from '@/api/data'
import { Button, Input, Label, Select } from '@/components/ui'

export default function Checkout() {
  const navigate = useNavigate(); const [data, setData] = useState({ items: [] }); const [address, setAddress] = useState(''); const [payment, setPayment] = useState('pix'); const [loading, setLoading] = useState(true); const [finishing, setFinishing] = useState(false); const [success, setSuccess] = useState(null)
  useEffect(() => { listCart().then(setData).catch(e => toast.error(e.message)).finally(() => setLoading(false)) }, [])
  const items = data.items || []; const total = items.reduce((sum, i) => sum + Number(i.subtotal || 0), 0)
  const finish = async () => { if (!address.trim()) return toast.error('Informe o endereço de entrega.'); setFinishing(true); try { const order = await checkout(items, null, address, payment); setSuccess(order) } catch (e) { toast.error(e.message) } finally { setFinishing(false) } }
  if (loading) return <div className="flex justify-center py-32"><div className="w-8 h-8 border-4 border-[#5A5FBF]/20 border-t-[#0D1273] rounded-full animate-spin" /></div>
  if (success) return <div className="max-w-xl mx-auto px-4 py-20 text-center"><div className="w-16 h-16 mx-auto rounded-full bg-green-100 text-green-700 flex items-center justify-center mb-5"><CheckCircle2 className="w-8 h-8" /></div><h1 className="text-3xl font-heading font-bold text-[#0D1273]">Pedido realizado!</h1><p className="text-gray-500 mt-2">Número do pedido: <strong>{success.id}</strong></p><p className="text-gray-500 mt-1">Total: <strong>R$ {Number(success.valor_total || total).toFixed(2)}</strong></p><p className="text-sm text-gray-400 mt-3">O pagamento ficou registrado como pendente.</p><div className="flex justify-center gap-3 mt-7"><Button variant="outline" onClick={() => navigate('/marketplace')}>Continuar comprando</Button><Button onClick={() => navigate('/orders')}>Ver meus pedidos</Button></div></div>
  return <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8"><Link to="/cart" className="inline-flex items-center text-sm text-gray-500 hover:text-[#0D1273] mb-6"><ArrowLeft className="w-4 h-4 mr-1" />Voltar ao carrinho</Link><h1 className="text-2xl md:text-3xl font-heading font-bold text-[#0D1273] mb-8">Checkout</h1>{!items.length ? <div className="bg-white rounded-2xl border border-gray-100 p-10 text-center text-gray-500">Seu carrinho está vazio.</div> : <div className="grid lg:grid-cols-[1fr_320px] gap-6"><div className="bg-white rounded-2xl border border-gray-100 p-6 space-y-6"><div><h2 className="font-semibold text-[#0D1273] mb-4">Entrega</h2><Label>Endereço de entrega</Label><div className="relative mt-1.5"><MapPin className="absolute left-3 top-3 w-4 h-4 text-gray-400" /><Input className="pl-10" value={address} onChange={e => setAddress(e.target.value)} placeholder="Rua, número, bairro, cidade - UF" /></div></div><div><Label>Forma de pagamento</Label><div className="relative mt-1.5"><CreditCard className="absolute left-3 top-3 w-4 h-4 text-gray-400" /><Select className="pl-10" value={payment} onChange={e => setPayment(e.target.value)}><option value="pix">PIX</option><option value="cartao">Cartão</option><option value="dinheiro">Dinheiro na entrega</option></Select></div><p className="text-xs text-gray-400 mt-2">Nesta versão, o pagamento é registrado como pendente; não há gateway de pagamento conectado ao schema atual.</p></div><div><h2 className="font-semibold text-[#0D1273] mb-3">Itens do pedido</h2><div className="space-y-3">{items.map(i => <div key={i.id} className="flex items-center justify-between text-sm"><div><p className="font-medium text-[#0D1273]">{i.quantity}× {i.product_name}</p><p className="text-xs text-gray-400">{i.seller_name}</p></div><span>R$ {Number(i.subtotal).toFixed(2)}</span></div>)}</div></div></div><div className="bg-white rounded-2xl border border-gray-100 p-5 h-fit"><p className="text-sm text-gray-500">Total</p><p className="text-3xl font-bold text-[#0D1273] mt-1">R$ {total.toFixed(2)}</p><p className="text-xs text-gray-400 mt-2">O estoque é validado novamente antes da criação do pedido.</p><Button className="w-full mt-5" disabled={finishing} onClick={finish}>{finishing ? 'Finalizando...' : 'Finalizar pedido'}</Button></div></div>}</div>
}
